Repository systemli/ansible-role-etherpad, pull requests merged in 2023-08, with the labels that each got.

#82 Ensure SSH directory is present, if SSH key is defined
  tasks/main.yml
Labels: bug

#84 Debian: add bookworm, drop buster
  .github/workflows/main.yml
  meta/main.yml
  molecule/default/molecule.yml
Labels: enhancement

#85 Remove NodeJS Dependency
  .github/workflows/galaxy.yml
  .github/workflows/main.yml
  README.md
  files/apt/preferences.d/deb.nodesource.com.pref
  meta/main.yml
  molecule/default/converge.yml
  molecule/default/molecule.yml
  requirements.yml
  tasks/main.yml
  tasks/preflight.yml
  vars/main.yml
Labels: feature

#86 🐛 Fix Plugin Installation
  defaults/main.yml
  handlers/main.yml
  molecule/default/converge.yml
  molecule/default/prepare.yml
  tasks/main.yml
Labels: bug

#88 Remove special handling for Redis
  tasks/main.yml
  tasks/redis.yml
Labels: feature

#90 Fix various linting issues
  .ansible-lint
  handlers/main.yml
  tasks/abiword.yml
  tasks/main.yml
  tasks/mysql.yml
Labels: chore

#92 🔥 Drop Plugin Support
  README.md
  defaults/main.yml
  molecule/default/converge.yml
  tasks/main.yml
Labels: feature

#93 Fix Quotation in settings.json
  defaults/main.yml
  molecule/default/converge.yml
  templates/settings.json.j2
Labels: bug
